# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 11:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='amigos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 8, 8, 6, 34, 746000), verbose_name='Data'),
        ),
    ]
