# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 14:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0003_auto_20171008_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='horaC',
        ),
        migrations.AlterField(
            model_name='viagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 11, 2, 41, 705000), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='empresa',
            field=models.CharField(max_length=255, verbose_name='Hora de Chegada'),
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
