# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0004_auto_20171009_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onibus',
            options={'ordering': ['modelo'], 'verbose_name': 'onibus', 'verbose_name_plural': 'onibus'},
        ),
        migrations.RemoveField(
            model_name='onibus',
            name='motorista',
        ),
        migrations.AlterField(
            model_name='viagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 11, 17, 57, 749000), verbose_name='Data'),
        ),
    ]
