# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 14:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0008_auto_20171009_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='horaS',
        ),
        migrations.AlterField(
            model_name='viagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 11, 47, 18, 852000), verbose_name='Data'),
        ),
    ]
