# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 11:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0010_auto_20171009_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 10, 10, 8, 57, 35, 945000), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 8, 57, 35, 946000), verbose_name='Data'),
        ),
    ]
