# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 18:51
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0013_auto_20171010_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilhete',
            name='poltrona',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='poltrona'),
        ),
    ]
