# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0014_auto_20171010_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.FileField(null=True, upload_to='fotos', verbose_name='Foto'),
        ),
    ]
