# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import rede.models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0015_user_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cpf',
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.FileField(null=True, upload_to=rede.models.user_directory_path, verbose_name='Foto'),
        ),
    ]
