# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0016_auto_20171012_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'cidade',
                'verbose_name_plural': 'cidades',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='estado')),
                ('sigla', models.CharField(max_length=3, verbose_name='sigla')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
            },
        ),
        migrations.AlterField(
            model_name='viagem',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='rede.Cidade'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='rede.Cidade'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='rede.Estado'),
        ),
    ]
