# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0017_auto_20171012_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='estado',
            field=models.CharField(max_length=255, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
