# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0018_auto_20171012_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='onibus',
        ),
        migrations.DeleteModel(
            name='Onibus',
        ),
    ]
