# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0019_auto_20171013_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_fb_id',
            field=models.CharField(max_length=255, null=True, verbose_name='UserId'),
        ),
    ]
