# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import rede.models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0020_user_user_fb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=rede.models.user_directory_path, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_fb_id',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='UserId'),
        ),
    ]
