# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poltrona', models.IntegerField(verbose_name='poltrona')),
            ],
            options={
                'ordering': ['passageiro'],
                'verbose_name': 'bilhete',
                'verbose_name_plural': 'bilhetes',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endere\xe7o')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Onibus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista', models.CharField(max_length=255, verbose_name='Motorista')),
                ('modelo', models.CharField(max_length=255, verbose_name='Modelo')),
            ],
            options={
                'ordering': ['motorista'],
                'verbose_name': 'onibus',
                'verbose_name_plural': 'onibus',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('telefone', models.IntegerField(verbose_name='telefone')),
                ('cpf', models.CharField(max_length=14, verbose_name='cpf')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=255, verbose_name='origem')),
                ('destino', models.CharField(max_length=255, verbose_name='destino')),
                ('horaS', models.CharField(max_length=255, verbose_name='Hora de Saida')),
                ('horaC', models.CharField(max_length=255, verbose_name='Hora de Chegada')),
                ('data', models.DateTimeField(default=datetime.datetime(2017, 9, 18, 11, 34, 23, 578129), verbose_name='Data')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='rede.Empresa')),
                ('onibus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Onibus', to='rede.Onibus')),
            ],
            options={
                'ordering': ['data'],
                'verbose_name': 'viagem',
                'verbose_name_plural': 'viagens',
            },
        ),
        migrations.AddField(
            model_name='bilhete',
            name='Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagem', to='rede.Viagem'),
        ),
        migrations.AddField(
            model_name='bilhete',
            name='passageiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passageiro', to='rede.Usuario'),
        ),
    ]
