# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 14:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 18, 11, 39, 0, 10231), verbose_name='Data'),
        ),
    ]
